//! How the native task launcher reads the stub `mise generate task-stubs` writes.
//!
//! Shared by the launcher (`crates/mise-shim` includes this file) and by mise, which has to agree
//! with the launcher on which copies run a task. Std only: the launcher has no dependencies.

/// Parse the stub body `generate task-stubs` writes into `(mise_bin, task)`, or `None` for
/// anything else.
///
/// The shape is fixed by the generator:
///
/// ```sh
/// #!/bin/sh
/// # generated by mise task-stubs
/// exec <mise-bin> run <task> "$@"
/// ```
///
/// Deliberately strict. A stub that does not match is a file mise did not write -- or wrote in a
/// shape this copy predates -- and running the wrong task is worse than falling back to the shim
/// behaviour, which is what a `None` here does.
pub(crate) fn parse_task_stub(contents: &str) -> Option<(String, String)> {
    let mut lines = contents.lines();
    if lines.next()? != "#!/bin/sh" {
        return None;
    }
    if lines.next()? != "# generated by mise task-stubs" {
        return None;
    }
    let command = lines.next()?;
    if lines.next().is_some() {
        return None;
    }
    let command = command.strip_prefix("exec ")?.strip_suffix(" \"$@\"")?;
    let (mise_bin, rest) = split_first_word(command)?;
    // The task name is interpolated raw by the generator, so whatever is left is it verbatim --
    // no unquoting, and no splitting on a space a task name is allowed to contain.
    let task = rest.strip_prefix("run ")?;
    if mise_bin.is_empty() || task.is_empty() {
        return None;
    }
    Some((mise_bin, task.to_string()))
}

/// Split off the first shell word of the stub's `exec` line, returning it and the rest.
///
/// Only the two shapes `shell_words::quote` produces are accepted: a bare word, and a
/// single-quoted one where an embedded `'` is written `'\''`. Anything else -- a double quote, a
/// backslash escape, an unterminated quote -- is not something mise wrote, so it is rejected
/// rather than guessed at. Written out here because the launcher has no dependencies and is not
/// worth giving one for three cases.
pub(crate) fn split_first_word(line: &str) -> Option<(String, &str)> {
    let Some(mut rest) = line.strip_prefix('\'') else {
        let (word, rest) = line.split_once(' ')?;
        if word.contains(['\'', '"', '\\']) {
            return None;
        }
        return Some((word.to_string(), rest));
    };
    let mut word = String::new();
    loop {
        let (chunk, after) = rest.split_once('\'')?;
        word.push_str(chunk);
        match after.strip_prefix(r"\''") {
            // `'\''` -- the quoted word continues with a literal `'`.
            Some(next) => {
                word.push('\'');
                rest = next;
            }
            // The closing quote, which has to be followed by the separator.
            None => return Some((word, after.strip_prefix(' ')?)),
        }
    }
}
